run-name: "ecr-deploy-nginx.yml | tag=sha-${{ github.sha }}"

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  IMAGE_TAG: sha-${{ github.sha }}
  ECR_REPO_NGINX: react-laravel-practice-nginx-ecs

jobs:
  deploy-all:
    name: deploy-nginx-ecr
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      #  AWS 認証 (OIDC ロール)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ECR_NGINX_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and push nginx image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -f ./docker/ecr/nginx/Dockerfile -t $ECR_REGISTRY/${{ env.ECR_REPO_NGINX }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPO_NGINX }}:$IMAGE_TAG
