run-name: "ecs-update-nginx.yml | env=${{ inputs.target_env }} / tag=${{ inputs.IMAGE_TAG_NGINX }}"

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG_NGINX:
        description: "Nginxのイメージタグ"
        required: true

      target_env:
        description: "デプロイ先環境"
        type: choice
        options:
          - stg
          - prod
        required: true
        default: stg

env:
  AWS_REGION: ap-northeast-1
  IMAGE_TAG_NGINX: ${{ inputs.IMAGE_TAG_NGINX }}
  ECS_TASK_DEF: practice-${{ inputs.target_env }}-main-task
  CONTAINER_NAME_NGINX: nginx-container
  ECS_CLUSTER: practice-${{ inputs.target_env }}-cluster
  ECS_SERVICE: practice-${{ inputs.target_env }}-main-service
  ECR_REPO_NGINX: react-laravel-practice-nginx-ecs

jobs:
  deploy-all:
    name: Update-ECS
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    permissions:
      id-token: write
      contents: read

    steps:
      #ソース取得
      - uses: actions/checkout@v4

      #  AWS 認証 (OIDC ロール)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ECS_UPDATE_NGINX_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # AWS account IDを取得
      - name: Get AWS account ID
        id: get-account-id
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "ACCOUNT_ID=${ACCOUNT_ID}" >> $GITHUB_ENV

        # 最新のタスク定義JSONをAWSからダウンロード
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEF }} \
          --query taskDefinition > task-definition.json

      # タスク定義のイメージURIを書き換え
      - name: Render nginx container
        id: render-nginx
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME_NGINX }}
          image: ${{env.ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/${{env.ECR_REPO_NGINX}}:${{env.IMAGE_TAG_NGINX}}

      # 新しいタスク定義を登録し、サービスを更新
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-nginx.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
